rm(list = ls())

library(rvest)
library(dplyr)
library(lubridate)
library(stringr)
library(googleLanguageR)
# unique Google translate API key used for translation - the path needs to be changed
gl_auth("/Users/gustawkempa/Desktop/Studia/Master/Master.Data/master-377713-d6f77365d167.json")


# links to separate chosen speeches by Spanish PM


links<- c('https://www.lamoncloa.gob.es/presidente/intervenciones/paginas/2020/prsp20200313.aspx',
          'https://www.lamoncloa.gob.es/presidente/intervenciones/paginas/2020/prsp28032020.aspx',
          'https://www.lamoncloa.gob.es/presidente/intervenciones/paginas/2020/rppg18042020.aspx',
          'https://www.lamoncloa.gob.es/presidente/intervenciones/paginas/2020/prsp22042020.aspx',
          'https://www.lamoncloa.gob.es/presidente/intervenciones/paginas/2020/prsp16052020.aspx',
          'https://www.lamoncloa.gob.es/presidente/intervenciones/paginas/2020/prsp07062020.aspx',
          'https://www.lamoncloa.gob.es/presidente/intervenciones/paginas/2020/prsp18062020.aspx',
          'https://www.lamoncloa.gob.es/presidente/intervenciones/paginas/2020/prsp20062020.aspx',
          'https://www.lamoncloa.gob.es/presidente/intervenciones/paginas/2020/prsp23072020.aspx',
          'https://www.lamoncloa.gob.es/presidente/intervenciones/paginas/2020/rpcm20200804.aspx',
          'https://www.lamoncloa.gob.es/presidente/intervenciones/paginas/2020/25082020.aspx',
          'https://www.lamoncloa.gob.es/presidente/intervenciones/paginas/2020/prsp16092020.aspx',
          'https://www.lamoncloa.gob.es/presidente/intervenciones/paginas/2020/prsp21092020.aspx',
          'https://www.lamoncloa.gob.es/presidente/intervenciones/paginas/2020/10102020_artprecuperacion.aspx',
          'https://www.lamoncloa.gob.es/presidente/intervenciones/paginas/2020/prsp151020.aspx',
          'https://www.lamoncloa.gob.es/presidente/intervenciones/paginas/2020/prsp05112020.aspx',
          'https://www.lamoncloa.gob.es/presidente/intervenciones/paginas/2020/23122020_articuloexpansion.aspx',
          'https://www.lamoncloa.gob.es/presidente/intervenciones/paginas/2021/08032021_s-nchezmujer.aspx',
          'https://www.lamoncloa.gob.es/presidente/intervenciones/paginas/2021/prsp06042021.aspx',
          'https://www.lamoncloa.gob.es/presidente/intervenciones/paginas/2021/prsp1242021.aspx',
          'https://www.lamoncloa.gob.es/presidente/intervenciones/paginas/2021/prsp14052021.aspx',
          'https://www.lamoncloa.gob.es/presidente/intervenciones/paginas/2021/prsp21052021-global.aspx',
          'https://www.lamoncloa.gob.es/presidente/intervenciones/paginas/2021/prsp19052021.aspx',
          'https://www.lamoncloa.gob.es/presidente/intervenciones/paginas/2021/prar20210622.aspx',
          'https://www.lamoncloa.gob.es/presidente/intervenciones/paginas/2021/prsp20210725.aspx',
          'https://www.lamoncloa.gob.es/presidente/intervenciones/paginas/2021/prsp20210901.aspx'
          )

# REMEMBER TO EXCLUDE Q&AS!!!!!
res <- tibble( titles = character(), dates = character(), speeches_ES = character(), links = character())

for (i in 1:length(links)) {
 res_temp <- matrix("", ncol = 4, nrow =1)
  res_temp[,1] <- links[i]
  page <- read_html(res_temp[,1])
 res_temp[,2] <- page %>% html_nodes('#h1Title') %>% html_text()
 res_temp[,3] <-  page %>% html_nodes('#ctl00_PlaceHolderMain_DisplayMode_noticia_pDate') %>% html_text()
  speech <- page %>% html_nodes('#MainContent p') %>% html_text()
  speech <- speech[-length(speech)]
  res_temp[,4] <- paste(speech[-1], collapse = " ")
  res <- rbind(res, res_temp)
}

data_ES <- res
colnames(data_ES) <- c("links", "titles", "dates", "speeches_ES")
data_ES$dates <- dmy(data_ES$dates)
# Adding manually the parts that did not work
data_ES$speeches_ES[26] <- 'Buenos días. Gracias a los medios de comunicación por cubrir esta comparecencia.
Buenos días a todos y a todas. Bueno, es tradición hacer un acto como este a la hora de inaugurar nuestro curso político. Este encuentro, de alguna manera entre distintas personalidades de diferentes ámbitos de la sociedad civil de nuestro país, pues cumple el papel simbólico de representar el encuentro de toda la sociedad española después de unos días merecidos de descanso y justo cuando reemprendemos nuestras obligaciones laborales y también nuestros hijos y nuestras hijas reemprenden en el curso escolar. Así que, en primer lugar, quisiera agradecer el que todos y todas hayan tenido a bien poder hacer un alto en sus apretadas agendas para poder compartir este encuentro. A fin de cuentas, nuestros padres y nuestras madres, que son nuestros mejores maestros, nos enseñaron que el comienzo de cada curso es por sí mismo una razón para hacer crecer en nosotros la voluntad de superación, de optimismo y de esperanza. Y ese mismo espíritu es el que nosotros siempre inculcamos a nuestros hijos y nuestras hijas cuando empieza el mes de septiembre.
Y en este caso, además, quiero subrayar el que en este nuevo comienzo trae además más y mejores razones para la esperanza. La sociedad española, que hay que decirlo una vez más, ha hecho un encomiable esfuerzo a lo largo de este año y medio tan duro, tan difícil en todos los ámbitos, desde el punto de vista social, familiar y también desde el punto de vista económico, empresarial y laboral, ansía tener una nueva etapa mejor y sus representantes, sobre todo los representantes políticos, debemos contribuir con nuestro trabajo a cumplir ese razonable deseo.
En este nuevo curso que abrimos, el nuevo gobierno, la sociedad civil, yo diría también que los agentes sociales estamos llamados a dos tareas fundamentales. La primera es a consolidar la recuperación económica que estamos viendo en los datos macroeconómicos. Y la segunda es a que esa recuperación llegue al bolsillo de todos los españoles y españolas en forma de más empleo, en forma de mejores salarios y en forma de pensiones más dignas.
Porque no va a haber una recuperación económica si no es una recuperación justa, si no llega a todos los estratos de nuestra sociedad, si no se expande a todos y cada uno de los pueblos y ciudades de España. Nadie puede quedar atrás. Este es el compromiso del Gobierno de España.
Por eso la voluntad del Gobierno es abordar una subida inmediata del salario mínimo interprofesional en lo que queda del año y continuar avanzando así en el objetivo electoral, en el compromiso electoral de alcanzar en el año 2023, al final de la legislatura, el 60 % del salario medio, que es en definitiva, lo que nos marca la Carta de Derechos Sociales del Consejo Europeo.
Y por eso hemos acordado con los agentes sociales y aprobado en el Consejo de Ministros el primer acuerdo de pensiones desde el año 2011, donde nos comprometemos a muchas cosas. Clarificamos las fuentes de financiación de nuestro sistema público de pensiones, pero sobre todo hacemos algo muy importante y es comprometernos por ley a la revalorización de las pensiones de nuestros mayores conforme al IPC.
Para ello, de nuevo pido el apoyo del conjunto de los grupos políticos en el Congreso de los Diputados para este importante acuerdo de los agentes sociales, que fue refrendado en un acuerdo del Consejo de Ministros.
Porque creo, honestamente, que entre todos, es decir, entre el Gobierno y el Poder Ejecutivo en consecuencia, el Poder Legislativo y también los agentes sociales, debemos hacer lo posible porque esa recuperación sea lo más justa posible.
Señoras y señores, la pandemia, lo hemos dicho en muchas ocasiones, a mí me lo han escuchado decir en multitud de ocasiones, ha supuesto una dura prueba para nuestra sociedad. Lo está siendo para el conjunto del planeta.
Ha puesto en cuestión los fundamentos más básicos de nuestra vida y también nuestras esperanzas. La viabilidad de miles de empresas, la viabilidad en consecuencia también de miles de empleos, nuestras relaciones sociales, familiares, la salud, la vida de nuestros seres queridos. Y en muchos y dolorosos casos, por desgracia, hemos sufrido también la pérdida de miles de compatriotas cuyo testimonio de vida siempre permanecerá en nuestra memoria colectiva.
Pero si lo pensamos bien, lo cierto es que por fin estamos superando esta dura prueba. Y ahora el objetivo, en consecuencia, es superar la pandemia de manera completa y recuperar la normalidad que disfrutábamos antes de que eclosionara el Covid 19.
El objetivo del nuevo gobierno para esta nueva etapa se resume en tres propósitos que me gustaría volver a sintetizar.
En primer lugar, seguir vacunando para proteger al conjunto de la población española.
En segundo lugar, como he dicho antes, propiciar una recuperación que sea lo más justa posible, es decir, que llegue al conjunto de hombres y mujeres de nuestro país, sobre todo a aquellos más vulnerables.
Y en tercer lugar, abordar la histórica tarea que tenemos de modernizar, tanto nuestra economía como nuestro tejido social, gracias a los fondos europeos.
Y yo creo que podemos lograrlo. Si hoy los españoles y españolas podemos mirar el futuro con una mayor confianza, con una mayor esperanza. Si hoy podemos hacerlo con más ambición que nunca, es precisamente porque hemos comprobado ante nosotros mismos y también ante el conjunto del mundo, nuestra capacidad para afrontar los grandes desafíos y también superar esos grandes desafíos.
Somos capaces de recuperarnos con rapidez, con fortaleza, como lo estamos haciendo durante estos meses largos de pandemia. Y sobre todo, la tarea que tenemos por delante es hacerlo con justicia social.
Porque lo cierto, lo cierto es que si echamos la vista atrás y comparamos hoy como estamos a como estábamos en septiembre del año pasado, es evidente, y ahí están los datos, que España está mucho mejor que hace un año. Pensemos por un instante en todo lo que hemos logrado en estos últimos doce meses.
En primer lugar, hace un año, la vacuna era una esperanza que aún no se había materializado. Hoy, esta semana, tal y como me comprometí a principios de año, el 70 % de la población española estará vacunada con pauta completa.
Más del 90 % de la sociedad española, que tiene más de 40 años, está vacunada con pauta completa. Y los jóvenes siguen el ejemplo de los mayores. Más del 70 % de aquellos con edades comprendidas entre 20 y 29 años y aquellos con edades comprendidas entre 12 y 19 años, ya tienen al menos una dosis administrada.
Y esto quiero ponerlo en valor porque en algunas ocasiones en el debate público se ha tratado de estigmatizar a este grupo de la población, a la gente más joven, con algunas de las fotos y las imágenes que hemos visto durante estos largos meses de pandemia.
Pero la respuesta de los jóvenes al proceso de vacunación, el compromiso con su salud y sobre todo con la salud de todos, es emocionante y es todo un orgullo. Y por tanto, desde el gobierno solo tenemos palabras de agradecimiento hacia ellos y también, por qué no decirlo, hacia sus padres y sus madres por haberles inculcado los valores de solidaridad y de compromiso social.
Pero sí quisiera decir que hay dos elementos que contribuyen a la esperanza cuando hablamos de la vacunación y por tanto de la inmunidad de grupo. El primero es que el ritmo de vacunación está siendo homogéneo en todos y cada uno de los territorios de nuestro país. Todas las comunidades autónomas se están aproximando por igual, si no han superado ya, el 70 % de la población con pauta completa.
Ello demuestra varias cosas. La primera de ellas, el acierto de la estrategia de vacunación. Y en segundo lugar, también el valor de la equidad en el acceso a la vacuna de todos y cada uno de los territorios de nuestro país.
Y junto con la cobertura homogénea de la vacunación en cuanto a los territorios, sí quisiera subrayar también que la cobertura está también siendo homogénea por edades, sin encontrar, a diferencia de lo que está ocurriendo en otros países, resistencias significativas. Y esto es importante porque estos dos hechos, la cobertura homogénea desde el punto de vista territorial y desde el punto de vista generacional, nos van a proteger frente a las futuras olas del Covid 19.
Solamente quiero compartir con ustedes un dato. La letalidad en esta última ola se encuentra entre el 0,1 y el 0,3%. Entre el 0,1 y el 0,3%. La letalidad en la primera ola fue del 12,9%.
Todo ello es evidente es gracias a la vacuna. Todo ello es gracias al buen hacer de los profesionales sanitarios que nunca nos cansaremos de reivindicar y lógicamente de agradecer su profesionalidad y su compromiso con el país. Todo ello es también gracias al compromiso de la sociedad española, que ve la vacunación no solo como un derecho, sino a diferencia de otros países, como un deber. El deber de protegerse y el deber de proteger al conjunto de la sociedad española.
Y esto, queridos amigos y amigas, en un país como el nuestro, tan poco dado a reconocer sus méritos, yo creo que el éxito de la vacunación es toda una lección de nuestro mejor patriotismo. Y así lo reconoce el Gobierno de España.
Un patriotismo, por cierto, que también es solidario, porque España no solamente se está vacunando, sino que también está ayudando a otros países a vacunarse. He de recordar que en la última Cumbre Iberoamericana en Andorra, el Gobierno de España se comprometió a donar antes de finalizar el año, 7,5 millones de dosis a una región muy importante para nuestro país como es Latinoamérica. Bueno, pues ya hemos donado más de 6 millones de dosis a esa región.
Amigos y amigas. Lo hemos dicho en muchas ocasiones, conforme avanza la vacunación, se acelera la recuperación económica. Recordemos como iniciábamos el curso en septiembre del año pasado y cómo lo estamos iniciando hoy.
El PIB cayó en el segundo trimestre del año 2020 un 21,5% interanual y en el año 2021 se ha recuperado en un 20% casi. Las previsiones de los organismos nacionales e internacionales sitúan a nuestro país como una de las principales economías que más va a crecer y con más vigor durante los próximos años. Vamos a recuperar los niveles de pre pandemia en el año 2022.
Y es cierto, es cierto y lo estamos viendo en los medios de comunicación, no hoy sino ya desde hace unos cuantos meses, que tanto Estados Unidos como la zona del euro, van a tener y van a sufrir una recuperación económica con alza de precios. Pero quiero también ser claro. La voluntad, ceo que de Europa, Estados Unidos y por supuesto también la voluntad del Gobierno de España, es que debemos continuar con los estímulos para consolidar la recuperación económica y también para abordar la modernización verde y digital que necesita la economía europea y por tanto la economía española.
Recordemos también cuál era la evolución del empleo hace un año y cuál es hoy. A principios de septiembre del año pasado teníamos 735.000 trabajadores y trabajadoras en ERTES. Hoy tenemos menos de 280.000, 274.000 trabajadores y trabajadoras. Son muchos, pero no son ni de largo, los que teníamos al principio de la pandemia.
Nuestro mercado laboral está batiendo récords tras récords de afiliación a la Seguridad Social y la cifra de cotizantes es ya superior a los niveles de la pandemia. En la anterior crisis, hay que recordar que esos niveles de pre pandemia, o mejor dicho, de pre crisis del año 2008, tardamos casi una década en poder recuperarlos.
Si lo miramos en términos sociales, el inicio del curso pasado, los niños y niñas cuando acudían a los colegios, sus padres y madres no sabían si se iban a cerrar las aulas como consecuencia de la explosión de contagios en los centros educativos de nuestro país. Hoy se preparan para un curso con la normalidad casi restablecida y gracias, y esto quiero también reconocerlo, al esfuerzo de todas las instituciones, pero en particular de la comunidad educativa, España ha sido uno de los pocos países de la Unión Europea, de los pocos países de la Unión Europea, en donde las aulas se han mantenido abiertas en un 99% durante el curso escolar 20/21.
Las competiciones deportivas habían comenzado con los estadios vacíos y hoy vuelven a escucharse los aplausos de los aficionados en las gradas. Y hoy, precisamente, también el Consejo Interterritorial va a debatir junto con las Comunidades Autónomas y el Ministerio de Sanidad, si podemos elevar la presencia de aficionados en los eventos deportivos.
Unos aplausos, por cierto, que suenan también en los teatros y en las salas de concierto, como sonaron en nuestros hogares cuando la cultura nos ayudó a sobre llevar los momentos más difíciles del confinamiento hace muy poco tiempo. Y esto, todo se debe a la entrega, a la entereza, la profesionalidad de nuestros creadores.
Hace un año todavía nuestros mayores estaban muy recluidos y muy preocupados por la situación del covid y hace muy poco tiempo estuve en Navalmoral de la Mata, una ciudad de Cáceres, hablando con los mayores en un centro de mayores, y ya este mes de septiembre iban a empezar a retomar las actividades en su centro de mayores.
No estamos como hace un año. Estamos mucho mejor. Es más, en pocos meses España va a contar con su propia vacuna, demostrando en consecuencia el vigor de nuestro sistema de investigación, de nuestro sistema de innovación, de la ciencia española. Demostrando también el acierto de algo que quiero poner en valor, sobre todo ante la comunidad empresarial de nuestro país, y es el camino de colaboración público privada que hemos abierto desde el poder ejecutivo y también con los agentes sociales durante estos largos meses de emergencia sanitaria, económica y social.
Porque esta historia, una historia colectiva de superación, porque es una historia colectiva de superación que estamos escribiendo entre todos y todas, no ha ocurrido por casualidad. Nada de lo que está ocurriendo es por casualidad. Lo hemos logrado gracias, y quiero ponerlo en valor, a la unidad de acción y a la lealtad demostradas por todos los actores institucionales, por los agentes sociales y por el conjunto de la sociedad civil.
Sin duda alguna, la unidad de la Unión Europea con esos Fondos europeos que tanto defendimos y abogamos porque se constituyeran durante los inicios de esta emergencia sanitaria, económica y social en Bruselas. A la unidad también, y quiero ponerlo en valor de todos los gobiernos. Y cuando digo todos los gobiernos, digo todos los gobiernos, de todo signo político, desde el Gobierno de España, a todos los gobiernos de las comunidades autónomas y sin duda alguna, también los gobiernos municipales.
Y también al diálogo social. Al papel jugado por los sindicatos y a los empresarios en este momento histórico que tanto habéis hecho, precisamente por garantizar la estabilidad y la paz social. Gracias a los sindicatos y a los empresarios por los once acuerdos alcanzados. Gracias por el compromiso con vuestro país, que es en definitiva, el compromiso con sus empresas y con sus trabajadores y trabajadoras.
Amigos y amigas en este nuevo tiempo de superación de la pandemia y, por tanto de recuperación, hay lecciones que no debemos olvidar. Y me gustaría compartir con algunos, con ustedes, algunas de esas lecciones.
La primera de ellas es la importancia del Estado. La importancia de lo público. La necesidad de que el estado del bienestar salga de este embate reforzado y no debilitado. Tiene que salir reforzada la sanidad pública, en particular, la atención primaria. Tiene que salir reforzada de este trance, de este embate, la educación, la formación profesional, la universidad pública. Tiene que salir reforzado ese pilar del Estado del bienestar que hemos construido en un tiempo récord durante lo que llevamos de legislatura, que es el ingreso mínimo vital, para acabar con una de las principales lacras que más avergüenza desde el punto de vista político y social a nuestro país como es la pobreza infantil.
Tiene que salir fortalecido nuestro sistema público de pensiones y también una nueva economía de los cuidados, que sin duda alguna tenemos que repensar como consecuencia de esta pandemia, para hacerla más digna que la actual a nuestros mayores.
Y cómo no, tiene que salir reforzado aquello que nos ha sacado de esta situación de pandemia, que es la investigación, que es la innovación, que es la ciencia.
Yo creo que esta crisis, esta emergencia sanitaria, económica y social es un enorme, y también yo diría una inolvidable lección de la exigencia de contar con un Estado del bienestar más fuerte y no más débil cuando salgamos definitivamente de esta crisis. Y quiero decirles que el Gobierno de España está comprometido con ello.
Junto con el fortalecimiento del Estado, yo diría que la segunda de las lecciones que tenemos que extraer de esta crisis, es la necesidad del impulso reformista. El valor de la modernización. Y digo bien, digo reformas, no digo contrarreformas.
Las contrarreformas, hemos tenido muchas a lo largo de esta última década. Las contrarreformas lo que hacen es recortar derechos, provocar desigualdad, aumentar la exclusión en un país ya con muchísima desigualdad y muchísima exclusión social, menoscaba a la postre la convivencia al minar la cohesión social en nuestro país.
Por tanto reformar significa para el Gobierno de España avanzar, y no involucionar. Y la agenda reformista que propone el Gobierno de España aborda las dos principales revoluciones que tenemos que afrontar a lo largo de la próxima década, que es, sin duda alguna, la revolución digital y la revolución verde.
Pero queremos hacerlo desde una cuádruple perspectiva integradora. Sin duda alguna la social, pero también la intergeneracional, porque los jóvenes tienen que ser los protagonistas de estos grandes cambios. También la de género en un país altamente desigual entre hombres y mujeres y por supuesto la cohesión territorial. A ello, lo saben ustedes bien, vamos a dedicar buena parte los Fondos europeos.
Y me gustaría detenerme, cuando hablamos de la agenda reformista, en este punto para abordar la compleja situación del sector energético y la evolución del mercado mayorista, que es objeto de debate en la opinión pública y en la opinión publicada como estamos viendo en los medios de comunicación.
Quiero subrayar el adjetivo de compleja porque es una situación compleja, a la cual no hay una única respuesta, sino una agenda reformista con medidas coyunturales, estructurales y con un compromiso de protección social hacia aquellos consumidores más vulnerables que el Gobierno viene desarrollando desde hace ya tres años.
Miren, yo no voy a perder el tiempo en revisar las acciones y las omisiones de anteriores Administraciones sobre este asunto y sus consecuencias. Que las hay. Creo que lo que debemos hacer desde el Gobierno de España es mirar al presente y al futuro. Y es lo que voy a hacer. Y en ese sentido quiero manifestar algo muy claro. El Gobierno se hace cargo de la preocupación social. Y por eso, el Gobierno ha actuado, actúa y seguirá actuando hasta solucionar el alza de los precios de la energía.
Hemos actuado. Hemos actuado. Hemos bajado el IVA del 21 al 10%. Hemos suspendido el impuesto del 7% sobre el valor de la producción de energía eléctrica. Hemos protegido a aquellos consumidores más vulnerables ampliando el Bono Social, aprobando el Bono Social Térmico para dar cobertura a los colectivos más vulnerables, estamos hablando de más de 1.100.000 beneficiarios.
Hemos actuado y estamos actuando, con la tramitación parlamentaria del Proyecto de Ley del Fondo Nacional de Sostenibilidad del Sistema Eléctrico y del Proyecto de Ley por la que se actúa sobre la retribución del CO2 no emitido del mercado eléctrico.
Por eso lo que estamos pidiendo los Grupos Parlamentarios es una tramitación parlamentaria rápida y la aprobación mayoritaria en el Congreso de los Diputados.
Estamos actuando. Actuamos, por ejemplo, con las subastas de energías de nueva potencia renovable. Este año 2021 dos subastas por un total de más de 6.000 MW. Actuamos con ayudas directas al autoconsumo, actuamos con ayudas directas a la eficiencia y rehabilitación energética. Actuamos también cuando impulsamos inversiones en la movilidad eléctrica por valor de más de 4.000 millones de euros.
Y vamos a continuar actuando, pero lo que tenemos que tener claro es que vamos a continuar actuando, siempre dentro del marco regulatorio europeo. Estableciendo las condiciones que permitan disminuir la volatilidad de la tarifa regulada, conocida como Precio Voluntario para el Pequeño Consumidor (PVPC) y también impulsando en Europa la adaptación de las reglas del mercado a un nuevo contexto de transición energética e incremento en la penetración de las energías renovables.
Por tanto, hemos actuado, estamos actuando y seguiremos actuando para dar respuesta a esta demanda social.
Pero quisiera poner este ejemplo como uno más de la agenda reformista que está poniendo en marcha el Gobierno de España. Y en ese sentido tanto el Congreso de los Diputados como los grupos parlamentarios que sustentan a este Gobierno, se han abierto a la constitución de una Comisión Parlamentaria de Estudio del sector energético en las Cortes Generales. Nosotros damos la bienvenida a esta Comisión y escucharemos las diferentes propuestas que tienen que poner encima de la mesa los grupos parlamentarios y los diferentes actores involucrados de manera directa o indirecta en el sector energético. Porque, créanme, escuchar, debatir, acordar y actuar son cuatro verbos con los que el Ejecutivo se siente totalmente comprometido.
Por lo tanto, amigos y amigas, reformas que nos permiten avanzar en el abordaje de estas dos grandes revoluciones, la digital y la ecológica, desde una perspectiva integradora.
Reformas como por ejemplo la Ley Educativa. Hemos asistido durante este verano a una crítica, a mi juicio infundada, diciendo poco menos que esta nueva Ley educativa supone un "adoctrinamiento" de los alumnos y alumnas en nuestro país. Y yo creo que no es tal.
Fíjense, educar en los valores de la igualdad de género, en un país donde estamos viendo que hay mujeres que por el hecho de ser mujeres son asesinadas. Educar en los valores de la sostenibilidad medioambiental, incentivar el estudio de las niñas, de las disciplinas stem, a mi juicio es avanzar en la calidad de nuestro sistema educativo. Es ampliar las capacidades y oportunidades de nuestros jóvenes. Es hacer una ciudadanía más crítica y, por lo tanto, más libre.
Y quien no entiende esto, es que no entiende el mundo en el que vive. Pero afortunadamente yo creo que en este debate son una minoría los que se sitúan en ese espacio.
Ayer aprobamos el Anteproyecto de la nueva ley de universidades. Y este mes aprobaremos el proyecto de Ley de Formación Profesional, que va a ser una auténtica revolución para garantizar la empleabilidad de nuestros jóvenes. En definitiva, el capital humano en sus distintas vertientes, la educación básica, la formación profesional, y la universitaria son también compromisos del gobierno de España.
El Gobierno, señoras y señores, va a continuar con su agenda reformista. No vamos a parar. Vamos a continuar haciendo avanzar a España. Logrando consolidar la recuperación económica y que ésta llegue a todas las capas de la sociedad y a todos los territorios de España.
Señoras y señores.
Ayer echando las cuentas veía que el Gobierno de España cumple hoy exactamente 603 días desde que se constituyó el 7 de enero del 2020. Y cada uno de esos 603 días el Gobierno ha actuado. Ha tomado decisiones, ha elaborado leyes, ha dotado de recursos y ha propiciado acuerdos. Ha contribuido a la necesaria e imprescindible estabilidad política e institucional para lograr las tareas de reforma y de modernización que exige nuestro país.
Es verdad que hemos actuado, a menudo, en condiciones inesperadas y extremas como no ha habido ningún Gobierno en la historia de nuestra democracia, porque hemos tenido que hacer frente, además de a nuestra agenda reformista, a una pandemia. Pero hemos actuado, y eso es lo que quiero trasladarles hoy, como lo trasladé hace un año. Este es un Gobierno de acción. Este es un Gobierno resuelto. Este es un Gobierno que va a hacer a España avanzar.
En los aproximadamente 850 días que quedan de legislatura hasta finales de 2023, seguirá siendo así. Ayer mismo, el Consejo de Ministros aprobó el Informe Anual de Evaluación Normativa correspondiente al Plan Anual Normativo del año 2020, así como también el Plan Anual Normativo para el año 2021.
Ambos informes reflejan precisamente la acción de un gobierno que avanza firmemente hacia el cumplimiento de sus compromisos electorales y de legislatura.
El informe refleja unas cifras que me gustaría compartir con ustedes. Un 84% de cumplimiento se ha realizado sobre las medidas contempladas en el Plan de 2020, para ser más precisos un 49% de normas previstas ya han sido aprobadas y un 35% se están tramitando.
Mientras que el plan para 2021 incluye 146 iniciativas. Repito 146 iniciativas. 6 leyes orgánicas, 27 leyes ordinarias y 113 reales decretos, además de una previsión a 3 años en coherencia con la planificación presupuestaria y el Plan de Recuperación, Transformación y Resiliencia, es decir con los Fondos europeos.
El Gobierno ya trabaja en la elaboración de los nuevos Presupuestos Generales del Estado. Unos presupuestos para la recuperación económica justa. Y que presentaremos entre finales del mes septiembre y principios del mes octubre.
Nuestro propósito es ambicioso: nuestro propósito es hacer de España un país aún mejor que antes de la pandemia.
Estos días hemos visto muchas cosas en los medios de comunicación. Hoy mismo también, cuando se cumple el primer día en 20 años sin presencia internacional en Afganistán, que evidentemente ha sacudido las conciencias del mundo entero.
Una crisis, por cierto, en la que España ha desempeñado y está desempeñando un papel que nos puede hacer sentir orgullosos del trabajo de todos nuestros servidores públicos. De las Fuerzas Armadas, los diplomáticos, la Guardia Civil, la sanidad internacional, de la Cruz Roja, de las ONG que han estado involucradas también en este operativo. Es el éxito de ellos, es un éxito colectivo y así lo siente y lo vive el Gobierno de España
Pero sí quisiera recordar que la Presidenta de la Comisión Europea dijo, en la visita a la base aérea de Torrejón de Ardoz que España ha representado el alma de Europa. España ha levantado, hay que reconocerlo y subrayarlo, la bandera de los valores europeos en el lugar más difícil y en el momento más adverso como hemos vivido estas ultima semanas.
La bandera de los valores de nuestra Constitución, a fin de cuentas no son tan ajenos, por los que tanto hemos luchado, y que son nuestra seña de identidad. Es la libertad, es la igualdad, es la solidaridad y el respeto a la dignidad humana.
Y para hacer esa España mejor necesitamos poner la realidad de nuestro país a la altura de nuestros valores como sociedad. Abordar una agenda reformista en torno a la digitalización y la transición ecológica, desde la cohesión social y territorial, desde la perspectiva de género y las mayores oportunidades que tenemos que dar a nuestros jóvenes, también en forma de una pronta la emancipación de sus hogares paternos y maternos.
Hacía referencia a las lecciones que no debemos olvidar. La importancia del Estado, de lo público, de reforzar el Estado del bienestar. Las transiciones se han acelerado como consecuencia de la pandemia y por tanto tenemos que acelerar e intensificar esa agenda reformista con la que está comprometido el Gobierno de España.
Pero quisiera finalizar haciendo referencia a dos cuestiones más. La primera, el valor de la colaboración público privada. Las inversiones que vamos a desplegar gracias a los Fondos europeos servirán, sobre todo, para animar la inversión privada. La clave es que sean sostenibles en el tiempo cuando acabe el liderazgo de la inversión pública.
Los Fondos que estarán dirigidos principalmente a que sean gestionados por las PYMES y la economía social. Y que contará también con proyectos estratégicos, los
llamados PERTES, que servirán para modernizar y transformar industrias muy relevantes para la buena marcha de nuestra economía. La presente y la futura.
Al PERTE del vehículo eléctrico y conectado, que ya hemos aprobado antes de que empezaran estas vacaciones, en el mes de julio, van a seguir otros que aprobaremos en los próximos meses: los vinculados a la salud de vanguardia, al sector aeroespacial, a la industria agroalimentaria, por citar algunos.
Y para su consecución, contamos, y quiero reivindicarlo, con una sólida experiencia. A lo largo de estos últimos meses, por ejemplo los créditos ICO desplegados en la fase de resistencia y reactivación ante la pandemia, han sido un éxito, porque nos han permitido salvar miles de empresas y en consecuencia cientos de miles, sino millones de empleos en nuestro país.
Todas estas experiencias como los créditos ICO, como las ayudas directas que estamos implementando, o como también la colaboración público-privada para el desarrollo de la vacuna española nos demuestran que, cuando trabajamos juntos, nuestro país logra todo lo que se propone.
Y quisiera compartir con ustedes una última lección que es el valor de la lealtad. Hay que apelar a la unidad pero también a la lealtad. No con el Gobierno de España, pero sí con nuestro pacto de convivencia: con la Constitución española.
En un contexto de crisis como el actual sin precedentes en los últimos 100 años, sin duda alguna estos últimos 40 años, esta emergencia social económica y sanitaria será recordada, sin duda alguna, en los libros de Historia. Como decía, en un contexto de crisis como la actual es tarea de todos impulsar la regeneración de nuestras instituciones. Y regenerar es renovar. Es cumplir con lo que nos obliga la Constitución.
Ninguna formación política tiene el derecho a incumplir sus obligaciones constitucionales. A situarse fuera de la Constitución. Ello menoscaba el prestigio de nuestra democracia y nuestra arquitectura constitucional. Y eso lo hace en el momento en que los ciudadanos y ciudadanas más necesitan de instituciones fuertes, de instituciones sólidas.
Por eso no es aceptable que instituciones como el gobierno de los jueces lleve 1.000 días sin renovarse. No hay precedentes en la historia democrática de nuestro país. No es razonable que permanezca bloqueada la renovación del Tribunal Constitucional, del Defensor del Pueblo, del Tribunal de Cuentas. Porque cortocircuitar el funcionamiento de los órganos constitucionales es faltar a la lealtad con el pacto de convivencia que representa nuestra Constitución.
Por eso como Presidente del Gobierno hago un nuevo llamamiento a la oposición para que vuelva al consenso constitucional y cumpla con su deber constitucional.
Señoras y señores, amigos y amigas, termino. Termino haciendo una referencia a lo que ocurrió el pasado mes de julio cuando celebramos en el Palacio Real, con el rey Felipe VI, un homenaje a todos los fallecidos por el covid 19, en particular a los familiares de los profesionales sanitarios que han estado en primera línea estos largos meses de pandemia. Miles de personas a las que hoy echamos de menos y a las que siempre vamos a recordar. Su memoria personal será guardada por familiares y amigos, pero su memoria civil depende de todos nosotros y nosotras. De nuestro esfuerzo para honrarles construyendo un país mejor, un país por el que muchos de ellos, sobre todo los mayores, lucharon en las décadas más duras de nuestra historia reciente.
Y esta, señoras y señores, es la agenda del Gobierno de España, ni más ni menos. Hacer de España un país mejor. Lograr que la recuperación se combine con justicia social. Hacerlo desde la unidad de los actores públicos y privados. Avanzar en una agenda reformista gracias a los Fondos europeos. Y ser fieles a las obligaciones y deberes que nos mandata la Constitución española.
De nuevo muchísimas gracias por su asistencia.'

data_ES$speeches_ES[25] <- 'INTERVENCIÓN DEL PRESIDENTE DEL GOBIERNO, PEDRO SÁNCHEZ.
Buenas tardes. Majestad, presidente de la Xunta de Galicia, galardonados, galardonas, enhorabuena.
En 1863, vieron la luz estas palabras de Rosalía de Castro: "Lugar más hermoso no hubo en la Tierra que aquel que yo miro, que aquel que me hiciera". Estos versos pertenecen a "Cantares gallegos", obra en la que la excelente escritora cantó y dignificó como nadie su territorio, Galicia: su gente, su paisaje y sus costumbres.
Rosalía de Castro quiso ofrecer una imagen real de la tierra que tanto amaba. Reivindicó la belleza de los campos, la fortaleza de su pueblo, y también mostró el dolor de una sociedad rural que luchaba contra la pobreza y que se veía en consecuencia abocada al sufrimiento de la emigración.
Fue en una casa en Camiño Novo, la entrada a la ciudad de Santiago de Compostela desde la carretera de Pontevedra, que conducía al casco histórico de la ciudad, donde nació Rosalía.
Hoy, ese Camiño Novo es la avenida Rosalía de Castro, y aquel lugar del que debían marcharse entonces los campesinos y campesinas a trabajar a los campos de Castilla, y que la misma Rosalía tuvo que abandonar en su juventud, es una joya, Patrimonio Cultural de la Humanidad.
Santiago de Compostela, destino final de la peregrinación jacobea, es un referente mundial de conservación del patrimonio material e inmaterial. El Camino de Santiago fue el primero de los Itinerarios Culturales Europeos, concedido por parte del Consejo de Europa en 1987. Y en 2004, se le concedió la categoría de Gran Itinerario Cultural Europeo.
Representa, en consecuencia, el vínculo entre la ciudadanía europea y el patrimonio cultural, un espacio donde la tolerancia, la libertad, el sentimiento de comunidad y la solidaridad entre diferentes pueblos y culturas son posibles, se hacen realidad y cada año.
El Camino de Santiago recibió, también, el premio Príncipe de Asturias de la Concordia 2004 por ser, y cito textualmente, "un lugar de peregrinación y de encuentro entre personas y pueblos que a través de los siglos se ha convertido en símbolo de fraternidad y vertebrador de la conciencia europea".
El Camino, como vía cultural, como ruta artística, como calzada también histórica o como sendero para deportistas y turistas, ha sido la "gran avenida cultural europea de estos últimos tiempos".
Hoy, con Su Majestad el Rey, , se ha convocado, como bien decía el presidente de la Xunta, la reunión del Real Patronato de la Ciudad de Santiago, después de 18 años, y es una noticia yo diría excelente, primero para Santiago de Compostela, querido alcalde, para Galicia, querido presidente y, sin duda alguna, para el conjunto del país, para España. A lo largo de estos años de intenso trabajo, el Real Patronato se ha volcado en la protección patrimonial de los innumerables bienes que atesora Compostela, pero me gustaría también recalcar que se ha volcado en la preservación de los bienes inmateriales. Porque lo intangible, tanto en Galicia como en Santiago, es tan valioso como lo tangible. El eco de los versos de Rosalía es tan valioso como los gruesos muros de sus mejores edificios.
La Catedral de Santiago, como casi todos los monumentos de esta ciudad única, luce ahora con todo su esplendor. La bulliciosa y luminosa almendra, con su enlosado de siglos, conservado en un estado excelente por manos sabias, ha podido soportar el paso de miles y miles de peregrinos y visitantes y, por supuesto, el caminar cotidiano de los habitantes de esta maravillosa ciudad. Santiago de Compostela no solo puede observarse y admirarse sino, y esto es lo más importante, puede vivirse. Se ha impedido que el tiempo borre nuestra memoria.
Parafraseando de nuevo a Rosalía de Castro, diría que "el sediento viajero que el camino atraviesa", en Galicia, tiene donde aliviarse. Esta tierra es, a la vez, agua, agua fresca, es también memoria, es cultura viva y es estímulo.
El Gobierno de España está profundamente involucrado en este bienio Xacobeo. El Camino de Santiago es motor económico y de visualización de la propia ciudad, de Galicia, de toda España, y en su promoción internacional debemos trabajar, como bien ha dicho el presidente, unidos. La colaboración institucional entre administraciones de distinto signo político es posible y se sostiene además a lo largo del tiempo. Creo que los resultados son extraordinarios.
Aquí se ha dicho que el año 2020 no ha sido fácil para nadie y en nuestra memoria siempre tendremos muy presentes a las víctimas del covid-19. Debido a la peor crisis sanitaria y económica del último siglo, el número de peregrinos y peregrinas en el Camino de Santiago cayó un 84,49% en 2020 respecto al año 2019. Y si analizamos la afluencia mes a mes, el comienzo de 2020 indicaba todo lo contrario, indicaba un año prometedor, ya que se superaban en enero y febrero los datos de peregrinos de 2019. Sin embargo, a partir de marzo de 2020las cifras cayeron en picado, con datos a cero, como no podía ser de otra manera, en abril y mayo. A pesar de un crecimiento significativo durante los meses de julio y agosto, volvieron a caer a partir de septiembre debido a la siguiente ola del covid. Pero gracias a la vacunación y gracias al esfuerzo de todos y todas, ahora estamos, como he dicho en muchísimas ocasiones, en un punto diferente, en un punto cargado y repleto de esperanza.
Y no hay mayor motor para la recuperación ni mayor símbolo de futuro que este: a día de hoy, en España se han administrado 52.879.267 dosis de vacunas contra el coronavirus. Cada una de ellas es una pequeña victoria. Más de 25 millones de españoles y españolas tienen la pauta completa, es decir, el 52,8% de nuestra población. Y, con una sola dosis, son 30 los millones de personas vacunadas, es decir, el 63,7% de la población española.
Aquí se ha dicho por parte del presidente de la Xunta y también por parte de Yolanda: empezamos hace muy poco, en el mes de diciembre, a finales del mes de diciembre del año pasado. Y hoy ya son 52,8% el porcentaje de la población con pauta completa.
Este ritmo de vacunación, que es imparable, es sin duda gracias al esfuerzo común conjunto de instituciones públicas, que también quiero poner en valor, amigos y amigas, del Ministerio de Sanidad, de las Consejerías de Sanidad de todo y cada uno de los gobiernos autonómicos, con independencia del signo político que sean, y por supuesto de todo el personal sanitario de España.
Una vez más, desde que comenzó la pandemia, podemos estar inmensamente orgullosos y agradecidos. Agradecidos a los profesionales sanitarios que día y noche trabajan para vacunar al conjunto de la población española. Pero también al conjunto de la población española que, sin ninguna objeción, sin ninguna resistencia, ha acudido masivamente para protegerse y, en consecuencia, proteger al conjunto de la sociedad gallega y española.
Creo que una de las lecciones que nos ha dejado esta pandemia es el valor incalculable de la investigación y de la ciencia, que es imprescindible, y el mérito de todas y cada una de las personas que hay detrás del sistema de salud español es enorme. Sin todos ellos, sin todas ellas, la recuperación no sería posible. El futuro de este país, ahora más que nunca, está en las mejores manos.
Galicia, como se ha dicho por parte del presidente de la Xunta, es la segunda Comunidad Autónoma con más personas inmunizadas a día de hoy, solo por detrás de la vecina Asturias. El 66,7% de la población gallega ya ha recibido la pauta completa. El 66,7%. Enhorabuena, gallegos y gallegas. Enhorabuena porque más de 1,3 millones de gallegos y gallegas están a salvo de la covid-19.
El dispositivo que ha llevado la vacuna a todas estas personas, y que sigue trabajando sin cesar, pues es histórico. Desde hace seis meses, no ha habido otra prioridad para todos ellos y para todas ellas y quiero también nombrarlos como bien ha hecho el presidente Feijóo: personal de enfermería, de salud pública, de servicios centrales, administrativos, farmacéuticos, informáticos…En fin, un largo etcétera.
Las personas que están detrás de todo esto son muchas, y a cada una de ellas le debemos ese gran paso. Porque el éxito de la vacunación en Galicia es también una noticia fabulosa para el conjunto de la sociedad española.
Porque este camino, si me permiten el símil, como el de Santiago, es el camino colectivo de compañerismo y de solidaridad, y porque, como tantas veces hemos dicho desde que comenzó la pandemia, solo saldremos de ella si estamos unidos, si estamos unidas.
Aquellas palabras, si me permiten, siguen siendo la única hoja de ruta, y estoy seguro de que el dispositivo de vacunación gallego, que hoy recibe la Medalla de Oro de Galicia por su enorme esfuerzo y dedicación, lo sabe a pies juntillas.
En el mes de diciembre de 2020, aquí lo ha relatado, la enfermera Yolanda Moares Castiñeiras dijo, al recibir la primera dosis de la vacuna, que aquello era "el principio del fin del COVID". Yolanda, es enfermera de Catoira y fue quien administró la vacuna a la primera persona que se vacunó en Galicia. Estaba haciendo Historia. Estabas haciendo Historia, para Galicia, para España y para el conjunto de Europa.
Hoy, en consecuencia, estamos aquí para celebrarlo, para honrar la memoria de los fallecidos como consecuencia del COVID, pero también para reconocer el mérito a todos y todas sus compañeros y compañeras, de los profesionales sanitarios: porque el principio del fin de la COVID ha llegado a nuestro país a través de vuestras manos. Así que, gracias, Yolanda. Por aquel día histórico y por todos los demás días históricos que venís desplegando durante estos largos meses de pandemia.
En este momento de incertidumbre, tras los durísimos meses pasados Porque la labor encomiable del servicio de salud pública gallego, y del español, no es labor de un día. Es una labor constante, y es una labor para el futuro.
Por todo esto, querría acabar celebrando que Galicia, en este Año Santo Xacobeo, está de fiesta. Por el éxito de la vacunación, por el trabajo de sus enormes profesionales en todos los ámbitos y por seguir siendo una parte imprescindible de nuestra memoria. Por hacer posible el Camino de Santiago, que es, hoy más que nunca, símbolo del camino que queremos recorrer juntos como país, como sociedad.
En este momento de incertidumbre, tras los durísimos meses pasados, nos comprometemos a liderar el camino hacia la recuperación, de la mano de un Año Santo Xacobeo que es especial y que, estoy seguro, será el de la esperanza y la revitalización.
Hoy, 25 de julio, festividad del apóstol Santiago, es el Día de Galicia, una tierra que todos los españoles, querido presidente, querido alcalde de Santiago, autoridades gallegas, amamos de forma muy especial. Por la bondad de sus gentes, por su Finisterre, por su Ribera Sacra, por su gastronomía, por su clima, por su lengua y sobre todo, hoy quiero reivindicar, por su solidaridad. Todo el mundo -sea cual sea su procedencia- habla bien de Galicia, y ese es un atributo que debemos proteger entre todos y todas.
Una de las prioridades del Gobierno de España, como todos ustedes saben, es el de la de cohesión territorial, el reto demográfico es uno de los enormes desafíos de este siglo urbano. Dotar, en consecuencia, a todos los ciudadanos y ciudadanas de los mismos derechos y los mismos servicios. Cuando hablamos de que en esta crisis no podemos dejar a nadie atrás no solo estamos hablando de las personas, lógicamente son ellas las principales protagonistas, pero también son los territorios, todos y cada uno de los territorios de España, todos y cada uno de los territorios de Galicia.
Galicia es una tierra con una identidad orgullosamente rural que merece que se atienda con urgencia ese desafío del reto demográfico. Necesita infraestructuras que la vertebren mejor y un esfuerzo de política públicas que lleven el Estado del Bienestar a cada rincón de su geografía.
Recogiendo el guante del presidente de la Xunta de Galicia, el Gobierno de España, en este sentido, está comprometido con Galicia, querido Alberto, como lo demuestran dos hitos, muy importantes, que van a mejorar la movilidad de los gallegos y las gallegas y que van a impulsar esa vertebración del territorio.
Por un lado, la llegada inminente de la Alta Velocidad; y por otro, la rebaja histórica de los peajes de la autopista del Atlántico, que aprobaremos en el próximo Consejo de Ministras y Ministros, cumpliendo en tiempo y forma nuestros compromisos con la sociedad gallega.
La tan esperada llegada del AVE a la nueva estación intermodal de Santiago dará a la ciudad y a toda la comunidad autónoma una accesibilidad a la altura de lo que necesitaba y demandaba.
Supondrá un antes y un después en la Historia de Galicia y, en consecuencia, en la Historia de toda España. Y convertirá a este territorio, a este país, a esta tierra -aún más- en un espacio incomparable de encuentro.
Y la Autopista del Atlántico, la AP9, la autopista más utilizada por los gallegos y gallegas, recibirá unas bonificaciones hasta el fin de la concesión que van a suponer un ahorro de 2.300 millones de euros para los ciudadanos y ciudadanas que circulan por ella.
Esta autopista, que vertebra Galicia de norte a sur, es un elemento imprescindible para la movilidad de las personas y también de las mercancías de Galicia, y la drástica reducción de sus peajes a partir de la próxima semana va a permitir desviar la circulación de rutas alternativas y por tanto, mejorar así algo que sé que es muy sentido por la sociedad gallega, y es la seguridad vial.
Y va a permitir, sobre todo y ante todo, que miles de gallegos y gallegas que la usan a diario, habitualmente tengan un alivio económico en sus bolsillos.
Tanto el AVE como las rebajas de la AP9 son una prueba inequívoca de la apuesta del Gobierno de España por esta Comunidad Autónoma, por Galicia. De la apuesta por lograr beneficios reales para sus ciudadanos y por abrir las puertas de Galicia a todos aquellos y aquellas que quieren conocerla.
Los millones de visitantes que sabemos que van a llegar, sin duda van a llegar a lo largo de los próximos años a Galicia deben encontrar la región que esperan, la región que es: universal, excepcional, deslumbrante en su belleza de siglos y acogedora en su hospitalidad, pero también. Y quiero subrayarlo, por su innovación, por su compromiso con lo verde, por su compromiso con la sostenibilidad, por su compromiso con la cohesión social, participativa y despierta en su oferta cultural.
A Galicia seguirán llegando, ni más ni menos que a pie, millones y millones de peregrinos y peregrinas, haciendo de ella el lugar único que es.
No existe otro lugar en Europa, me atrevería a decir, amigos y amigas, que pueda contar esta hazaña: que gente de todo el mundo, proveniente de todas partes del mundo, recorra, durante días, con una mochila a su espalda, las sendas que se iniciaron en el siglo IX con el descubrimiento de la tumba del Apóstol Santiago el Mayor, y que confluyen en Santiago de Compostela, encuentro final de tantos, y tantos, y tantos, caminos históricos.
Aunemos esfuerzos, entre todos y todas, yo creo que esta es la gran lección que tenemos que extraer de la pandemia, aunar esfuerzos entre todos y todas, para seguir haciendo de Santiago, de Galicia y de España lo que somos, referentes mundiales. Hagamos juntos, también, este camino.
Muchísimas gracias.'

data_ES$speeches_ES[15] <- 'Buenos días desde Madrid.
Hoy conmemoramos el Día Internacional de las Mujeres Rurales, en un momento crucial para todo el mundo porque atravesamos, como bien sabéis, una emergencia sanitaria, y como consecuencia de ella también una emergencia económica y social sin precedentes por el COVID-19.
Y quiero aprovechar esta ocasión para daros las gracias a todas, en cada uno de los rincones desde los que me escucháis. Gracias de verdad. Porque si existe una deuda, o una de ellas, al menos, esa es con la visibilidad de las mujeres rurales en la lucha contra esta pandemia.
El sector agroalimentario en nuestro país, lo sabéis muy bien vosotras, nos ha abastecido a todos, a todas, subrayando la importancia de vuestra labor.
Las sanitarias de nuestros pueblos y de nuestras ciudades -reconociendo que la mayoría sois mujeres- os habéis dejado la piel en la carretera para dar asistencia a todos vuestros pacientes.
Los profesores, o mejor dicho, las profesoras, porque también hay que reconocer que es una mayoría de mujeres, y las maestras, habéis atendido a vuestras alumnas, a vuestros alumnos, en muchas ocasiones casi sin recursos.
En definitiva, cito algunos ejemplos, pero mi agradecimiento es global, también con nuestras mayores, símbolo de resistencia, de sabiduría y sin duda alguna, también de superación.
Así veo y así vemos desde el Gobierno a las mujeres rurales de nuestro país: como un motor incuestionable al que hay que escuchar mejor y reconocer cada día más. Las mujeres rurales sois emprendimiento, sois innovación, sois también compromiso con la tierra, sois en definitiva el futuro del medio rural en nuestro país. Vuestra palabra siempre hay que traducirla en acción y vuestras demandas en oportunidades.
Por eso es fundamental que lideréis y que participéis en todas las políticas, porque no podemos permitir que esta situación haga desaparecer todo lo que hemos logrado durante estos últimos años.
El reto demográfico es un reto de todos. De todas. Como el reto de la igualdad es un reto de todos, de todas. La igualdad en el campo, en la educación o en las empresas familiares.
Si las mujeres rurales avanzan, avanza el conjunto de la sociedad, avanzamos todos. Avanzan todos nuestros territorios, avanza nuestra sociedad y avanza sin duda alguna también nuestra economía.
Vuestro reto es el mío: lograr que cada persona, viva donde viva, tenga las mismas oportunidades.
Que haya igualdad de oportunidades en todos y cada uno de los territorios.
Así que contáis conmigo. Contáis con un Gobierno feminista que pone en el acento en las transformaciones de nuestro país, en la lucha por la igualdad y en la lucha contra la despoblación.
Una igualdad y una lucha hoy es más urgente que nunca porque son las mujeres las que por desgracia nuevamente están sufriendo los efectos de esta crisis. Así que mucho ánimo y buen congreso.'

# Getting rid of the Q&A parts
data_ES$speeches_ES <- str_extract(data_ES$speeches_ES, "^(.*?)(?=(P:|PREGUNTA:|P[.-])|$)")

data_ES$speeches_ES[27]

data_ES$count <- str_count(data_ES$speeches_ES, "\\w+")
data_ES$titles <- gsub("\n", "", data_ES$titles)
data_ES$speeches_ES <- gsub("\n", "", data_ES$speeches_ES)

topics_EN <- gl_translate(t_string = data_ES$titles, target = "en",
                                  format = "text", model = "nmt")[1]
speeches_EN <- gl_translate(t_string = data_ES$speeches_ES, target = "en",
                                    format = "text", model = "nmt")[1]
data <- cbind(data_ES,topics_EN ,speeches_EN)
colnames(data) <- c("links", "topics", "dates", "speeches_ES","len", "topics_EN", "speeches_EN")
write.csv(data, 'datasets/speeches/speeches_ES_translated')
